org: mmarulandc
console: true
service: portfolio-serverless-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource:
            - arn:aws:dynamodb:us-east-1:951079211721:table/PortfolioTable

plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  createUser:
    handler: src/controllers/user.createUser
    events:
      - httpApi:
          path: /user
          method: post
  updateUser:
    handler: src/controllers/user.updateUser
    events:
      - httpApi:
          path: /user/{portfolioId}
          method: put
  getAllUsers:
    handler: src/controllers/user.getAllUsers
    events:
      - httpApi:
          path: /user
          method: get
  getUser:
    handler: src/controllers/user.getUser
    events:
      - httpApi:
          path: /user/{portfolioId}
          method: get

resources:
  Resources:
    PortfolioTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PortfolioTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: portfolioId
            AttributeType: S
        KeySchema:
          - AttributeName: portfolioId
            KeyType: HASH
